[package]
name = "my_database_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8", features = [
    "runtime-tokio-native-tls",
    "postgres",
    "sqlite",
    "mysql",
    "any",
    "chrono",
    "uuid",
] }
tokio = { version = "1", features = ["full"] }
my_database_manager_macros = { path = "./my_database_manager_macros" }
